routes/web.php
<?php


use Illuminate\Support\Facades\Route;
use App\Http\Livewire\CategoriesController;
use App\Http\Livewire\ProductsController;
use App\Http\Livewire\CoinsController;
use App\Http\Livewire\PosController;
use App\Http\Livewire\RolesController;
use App\Http\Livewire\PermisosController;
use App\Http\Livewire\AsignarController;
use App\Http\Livewire\UsersController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('categories',CategoriesController::class);
Route::get('products', ProductsController::class);
Route::get('coins', CoinsController::class);
Route::get('pos', PosController::class);
Route::get('roles', RolesController::class);
Route::get('permiso', PermisosController::class);
Route::get('asignar', AsignarController::class);
Route::get('users', UsersController::class);

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $fillable=['name','barcode','cost','price','stock','alerts','image','category_id'];
    public function category(){
        #TODO: a qué categoría pertenece el producto?
        return $this->belongsTo(Category::class);
    }
    public function getImagen2Attribute()
    {
        if(file_exists('storage/products/'.$this->image))
        return $this->image;
        else
        return 'noimg.jpg';

    }
}

app/Http/Livewire/AsignarController.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Livewire\WithPagination;
use DB;

class AsignarController extends Component
{   use WithPagination;

    public $role, $componentName,$pageTitle,$permisosSelected = [], $old_permissions =[];
    private $pagination = 10;

    public function paginationView()
    {
        return 'vendor.livewire.bootstrap';
    }

    public function mount()
    {
        $this->role = 'Elegir';
        $this->pageTitle='Listado';
        $this->componentName ='Asignar Permisos';       
    }
 

    public function render()
    {   $permisos=Permission::select('name','id',DB::raw("0 as checked"))
        ->orderBy('name','asc')
        ->paginate($this->pagination);
        if($this->role!='Elegir'){
            $list=Permission::join('role_has_permissions as rp','rp.permission_id','permissions.id')
            ->where('role_id',$this->role)->pluck('permissions.id')->toArray();
            $this->old_permissions=$list;
        }
        if($this->role!='Elegir'){
            foreach ($permisos as $permiso) {
                $role=Role::find($this->role);
                $tienePermiso=$role->hasPermissionTo($permiso->name);
                if($tienePermiso){
                    $permiso->checked=1;
                }
            }
        }
        return view('livewire.asignar.asignar',['roles'=>Role::orderBy('name','asc')->get(),'permisos'=>$permisos])
        ->extends('layouts.themes.app')
        ->section('content');
    }
    public $listeners=['revokeall'=>'RemoveAll'];
    public function RemoveAll(){
        if($this->role=='Elegir')
        {
            $this->emit('sync-error','Selecciona un rol valido');
            return;
        }
        $role=Role::find($this->role);
        $role->syncPermissions([0]);
        $this->emit('removeall',"Se revocaron todos los permisos al role $role->name");

    }
    public function SyncAll(){
        if($this->role=='Elegir'){
            $this->emit('sync-error','Selecciona un role válido');
            return;
        }
        $role=Role::find($this->role);
        $permisos=Permission::pluck('id')->toArray();
         $role->syncPermissions($permisos);

        $this->emit('syncall',"Se sincronizaron todos los permisos");
    }
    public function syncPermiso($state,$permisoName){
        if($this->role!='Elegir'){
            $roleName=Role::find($this->role);
            if($state){
                $roleName->givePermissionTo($permisoName);
                $this->emit('permi',"Permiso asignado correctamente");
            }else{
                $roleName->revokePermissionTo($permisoName);
                $this->emit('permi',"Permiso eliminado correctamente");
            }
        }else{

            $this->emit('permi',"Elige un role válido");
        }
    }
}

app/Http/Livewire/Categoriescontroller.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\Category;
use Illuminate\Support\Facades\Storage;
use Livewire\WithFileUploads;
use Livewire\WithPagination;

class CategoriesController extends Component
{
    use WithFileUploads;
    use WithPagination;
    public $name,$search,$image,$selected_id,$pageTitle,$componentName;
    private $pagination=5;
    public function mount(){
        $this->pageTitle='Listado';
        $this->componentName='Categorías';
    }
    public function paginationView(){
        return 'vendor.livewire.bootstrap';
    }
    public function render()
    {
        if(strlen($this->search)>0)
            #TODO:Metodo where=Nombre de la columna,operador(en este caso like),operador para buscar letra en columna
            $data=Category::query()
            ->where('name','like','%'.$this->search.'%')->paginate($this->pagination);
        else
            $data=Category::orderBy('id','desc')->paginate($this->pagination);
        return view('livewire.category.categories',['categories'=>$data])
        ->extends('layouts.themes.app')
        ->section('content');
    }
    public function Edit($id)
    {
        $record=Category::find($id);
        $this->name=$record->name;
        $this->selected_id=$record->id;
        $this->image=null;
        $this->emit('show-modal','show modal!'); 
    }
    public function Store(){
        $rules=[
            'name'=>'required|unique:categories|min:3'
        ];
        $messages=[
            'name.required'=>'Nombre de la categoría es requerido',
            'name.unique'=>'Ya existe el nombre de la categoría',
            'name.min'=>'El nombre de la categoría debe tener al menos 3 caracteres'
        ];
        $this->validate($rules,$messages);
        $category=Category::create(['name'=>$this->name]);
        $customfileName;
        if ($this->image) {
            # code...
            #TODO:funcion para asignar id único y anexarle la extensión que ingresó el usuario
            $customfileName=uniqid().'_.'.$this->image->extension();
            $this->image->storeAs('public/categories',$customfileName);
            $category->image=$customfileName;
            $category->save();
        }
        $this->resetUI();
        #TODO:Emitir llamado para realizar la acción de 
        $this->emit('category-added','Categoria Registrada');
    }
    public function Update(){
        $rules=[
            #TODO: Filtra el nombre de la categoría y activa el mensaje por el unique
            'name'=>'required|unique:categories|min:3,name,{$this->selected_id}'
        ];
        $messages=[
            'name.required'=>'Nombre de la categoría es requerido',
            'name.unique'=>'Ya existe el nombre de la categoría',
            'name.min'=>'El nombre de la categoría debe tener al menos 3 caracteres'
        ];
        #TODO:Validar las reglas
        $this->validate($rules,$messages);
        #TODO: Buscar dentro del Category(tabla) con el id
        $category=Category::find($this->selected_id);
        #TODO:Actualizar el nombre con name del formulario
        $category->update([
            'name'=>$this->name
        ]);
        #TODO:Validar imagenes
        if($this->image)
        {
            #TODO:Crear nombre unico
            $customfileName=uniqid().'_.'.$this->image->extension();
            $this->image->storeAs('public/categories',$customfileName);
            $imageName=$category->image;
            #TODO:Recuperar nombre anterior
            $category->image=$customfileName;
            $category->save();
            #TODO:Validar si imagen es nulla
            if($imageName!=null)
            {#TODO:Si el archivo existe lo borrara
                if(file_exists('storage/categories'.$imageName))
                {
                    unlink('storage/categories'.$imageName);
                }
            }
        }
        $this->resetUI();
        #TODO:Emitir llamado para realizar la acción de 
        $this->emit('category-updated','Categoria Actualizada ');

    }
     public function resetUI(){
            $this->name='';
            $this->image=null;
            $this->search='';
            $this->selected_id=0;
     }
     protected $listeners=[
        'deleteRow'=>'Destroy'
     ];
     public function Destroy(Category $category){
        //$category=Category::find($id);
        //dd($category);
        $imageName=$category->image;
        $category->delete();
        if($imageName!=null){
            unlink('storage/categories/'.$imageName);
        }
        $this->resetUI();
        $this->emit('category-deleted','Categoria Eliminada1');
     }
}

app/Http/Livewire/CoinsController.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\Denominations;
use Illuminate\Support\Facades\Storage;
use Livewire\WithFileUploads;
use Livewire\WithPagination;
class CoinsController extends Component
{
    public $componentName,$pageTitle,$selected_id,$image,$search,$type,$value,$pagination;
    use WithPagination;
	use WithFileUploads;
    public function paginationView(){
        return 'vendor.livewire.bootstrap';
    }
    public function mount(){
        $this->componentName='Denominaciones';
        $this->pageTitle='Listado';
        $this->type='Elegir';
        $this->pagination=5;
        $this->selected_id=0;

    }
    public function render()
    {
    
            # code...
            if(strlen($this->search)>0)
            #TODO:Metodo where=Nombre de la columna,operador(en este caso like),operador para buscar letra en columna
            $data=Denominations::query()
            ->where('type','like','%'.$this->search.'%')
            ->orWhere('denominations.value', 'like', '%' . $this->search . '%')
            ->paginate($this->pagination);
        else
            $data=Denominations::orderBy('id','desc')->paginate($this->pagination);
        
        return view('livewire.denominations.coins',[
            'data'=>$data
        ])
        ->extends('layouts.themes.app')
        ->section('content');
    }
    public function Edit($id)
    {
        $record=Denominations::find($id,['id','type','value','image']);
        $this->type=$record->type;
        $this->value=$record->value;
        $this->selected_id=$record->id;
        $this->image=null;
        $this->emit('show-modal','show modal!'); 
    }
    public function Store(){
        $rules=[
            'type'=>'required|not_in:Elegir',
            'value'=>'required|unique:denominations'
        ];
        $messages=[
            'type.required'=>'El tipo es requerido',
            'type.not_in'=>'Elige un valor para el tipo distinto a Elegir',
            'value.required'=>'El valor es requerido'
        ];
        $this->validate($rules,$messages);
        $denominations=Denominations::create([
            'type'=>$this->type,
            'value'=>$this->value
        ]);
        
        if($this->image)
        {
            $customFileName=uniqid().'_.'.$this->image->extension();
            $this->image->storeAs('public/denominations',$customFileName);
            $denominations->image=$customFileName;
            $denominations->save();
        }
        $this->resetUI();
        $this->emit('denomination-added','Denominaición Registrada');
    }
    public function Update()
    {
    	$rules =[
    		'type' => 'required|not_in:Elegir',
            #TODO: Valor único en la tabla sobre value y seleccionando el id
    		'value' => "required|unique:denominations,value,{$this->selected_id}"
    	];

    	$messages =[
    		'type.required' => 'El tipo es requerido',
    		'type.not_in' => 'Elige un tipo válido',
    		'value.required' => 'El valor es requerido',
    		'value.unique' => 'El valor ya existe'
    	];

    	$this->validate($rules, $messages);


    	$denomination = Denominations::find($this->selected_id);
    	$denomination->update([
    		'type' => $this->type,
    		'value' => $this->value
    	]);

    	if($this->image)
    	{
    		$customFileName = uniqid() . '_.' . $this->image->extension();
    		$this->image->storeAs('public/denominations', $customFileName);
    		$imageName = $denomination->image;

    		$denomination->image = $customFileName;
    		$denomination->save();

    		if($imageName !=null)
    		{
    			if(file_exists('storage/denominations' . $imageName))
    			{
    				unlink('storage/denominations' . $imageName);
    			}
    		}

    	}

    	$this->resetUI();
    	$this->emit('denomination-updated', 'Denominación Actualizada');
    }
    public function resetUI() 
    {
    	$this->type ='';
    	$this->value ='';
    	$this->image = null;
    	$this->search ='';
    	$this->selected_id =0;
    }


	protected  $listeners = [
		'deleteRow' => 'Destroy'
	];

    public function Destroy(Denominations $denominations)
    {   	
    	
    	$imageName = $denominations->image; 
    	$denominations->delete();

    	if($imageName !=null) {
    		unlink('storage/denominations/' . $imageName);
    	}

    	$this->resetUI();
    	$this->emit('denomination-deleted', 'Denominación Eliminada');

    }



}

app/Http/Livewire/PermisosController.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Livewire\WithPagination;
use App\Models\User;
use DB;

class PermisosController extends Component
{   
    use WithPagination;
    public $permissionName,$search,$selected_id,$pageTitle,$componentName;
    private $pagination=10;
    public function paginationView(){
        return 'vendor.livewire.bootstrap';
    }
    public function mount(){
        $this->pageTitle='Listado';
        $this->componentName='Permisos';
    }
    public function render()
    {   
        if(strlen($this->search)>0)
            $permisos=Permission::where('name','like','%'.$this->search.'%')
                    ->paginate($this->pagination);
        else
        $permisos = Permission::orderBy('name','asc')->paginate($this->pagination);
             
        return view('livewire.permisos.permisos',['permisos' => $permisos])
        ->extends('layouts.themes.app')
        ->section('content');
    }
    public function CreatePermission(){
        $rules=['permissionName'=>'required|min:2|unique:permissions,name'];
        $messages=[
            'roleName.required'=>'El nombre del permiso es requerido',
            'roleName.unique'=>'El permiso ya existe',
            'roleName.min'=>'El nombre del permiso debe tener al menos dos carácteres'
        ];
        $this->validate($rules,$messages);
        Permission::create(['name'=>$this->permissionName]);
        $this->emit('permiso-added','Se registró el permiso con exito');
        $this->resetUI();

    }
    public function Edit(Permission $permiso){
        //$role=Role::find($id);
        $this->selected_id=$permiso->id;
        $this->permissionName=$permiso->name;
        $this->emit('show-modal','Show modal');
        }
    public function UpdatePermission(){
        #TODO:Filtrar que el rol sea único en la tabla roles en la columna nombre, será un id único en la fila
        $rules=['permissionName'=>'required|min:2|unique:permissions,name,{$this->selected_id}'];
        $messages=[
            'roleName.required'=>'El nombre del permiso es requerido',
            'roleName.unique'=>'El permiso ya existe',
            'roleName.min'=>'El nombre del rol debe tener al menos dos carácteres'
        ];
        $this->validate($rules,$messages);
        $permiso=Permission::find($this->selected_id);
        $permiso->name=$this->permissionName;
        $permiso->save();
        $this->emit('permiso-updated','Se actualizo el permiso con éxito');
        $this->resetUI();

    }
    protected $listeners=['destroy'=> 'Destroy'];
    public function Destroy($id){
        $rolesCount=Permission::find($id)->getRoleNames()->count();
        if($rolesCount>0){
            $this->emit('permiso-error','No se puede eliminar el permiso porque tiene roles asociados');
            return;

        }
        Permission::find($id)->delete();
        $this->emit('permiso-deleted','Se eliminó el permiso con éxito');
    }
    public function resetUI(){
        $this-> permissionName='';
        $this-> search='';
        $this-> selected_id=0;
        $this->resetValidation();
    }

}

app/Http/Livewire/Search.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Search extends Component
{   public $search;
    public function render()
    {
        return view('livewire.search');
    }
}

resources/views/livewire/products/form.blade.php
@include('common.modalHead')
<div class="row">
    <div class="col-sm-12 col-md-8">
        <div class="form-group">
            <label>Nombre</label>
            <!-- #TODO: con el wire:model.lazy="name" se puede capturar el valor del name -->
            <input type="text" wire:model.lazy="name" class="form-control product-name" placeholder="ej: Curso Laravel" autofocus>
        </div>
        @error('name')<span class="text-danger er">{{$message}}</span>@enderror
    </div>
    <div class="col-sm-12 col-md-8">
        <div class="form-group">
            <label>Código</label>
            <!-- #TODO: con el wire:model.lazy="name" se puede capturar el valor del name -->
            <input type="text"data-type="currency" wire:model.lazy="barcode" class="form-control" placeholder="ej:234589666">
        </div>
        @error('barcode')<span class="text-danger er">{{$message}}</span>@enderror
    </div>
    <div class="col-sm-12 col-md-8">
        <div class="form-group">
            <label>Costo</label>
            <!-- #TODO: con el wire:model.lazy="name" se puede capturar el valor del name -->
            <input type="text" data-type="currency"wire:model.lazy="cost" class="form-control" placeholder="ej:0.00">
        </div>
        @error('cost')<span class="text-danger er">{{$message}}</span>@enderror
    </div>
    <div class="col-sm-12 col-md-8">
        <div class="form-group">
            <label>Precio</label>
            <!-- #TODO: con el wire:model.lazy="name" se puede capturar el valor del name -->
            <input type="text" data-type="currency"wire:model.lazy="price" class="form-control" placeholder="ej:0.00">
        </div>
        @error('price')<span class="text-danger er">{{$message}}</span>@enderror
    </div>
    
    <div class="col-sm-12 col-md-8">
        <div class="form-group">
            <label>Stock</label>
            <!-- #TODO: con el wire:model.lazy="name" se puede capturar el valor del name -->
            <input type="number" data-type="currency"wire:model.lazy="stock" class="form-control" placeholder="ej:0">
        </div>
        @error('stock')<span class="text-danger er">{{$message}}</span>@enderror
    </div>
    <div class="col-sm-12 col-md-8">
        <div class="form-group">
            <label>Alertas</label>
            <!-- #TODO: con el wire:model.lazy="name" se puede capturar el valor del name -->
            <input type="number" wire:model.lazy="alerts" class="form-control" placeholder="ej:10">
        </div>
        @error('alerts')<span class="text-danger er">{{$message}}</span>@enderror
    </div>
    <div class="col-sm-12 col-md-8">
        <div class="form-group">
            <label>Categorias</label>
            <!-- #TODO: con el wire:model.lazy="name" se puede capturar el valor del name -->
            <select class="form-control" wire:model='categoryid'>
                <option value="Elegir">Elegir</option>
                @foreach($categories as $category)
                <option value="{{$category->id}}" >"{{$category->name}}"</option>
                @endforeach
            </select>
            @error('categoryid')<span class="text-danger er">{{$message}}</span>@enderror
        </div>
        
    </div>
    <<div class="col-sm-12 col-md-8">
<div class="form-group custom-file">
	<input type="file" class="custom-file-input form-control" wire:model="image"
	accept="image/x-png, image/gif, image/jpeg"  
	 >
	 <label class="custom-file-label">Imágen {{$image}}</label>
	 @error('image') <span class="text-danger er">{{ $message}}</span>@enderror
</div>
</div>

</div>

@include('common.modalFooter')

resources/views/livewire/products/products.blade.php
<div class="row sales layout-top-spacing">
<div class="col-sm-12">
    <div class="widget widget-chart-one">
        <div class="widget-heading">
            <h4 class="card-title">
                <!-- #TODO: COMPONENTES DE NOMBRES Y TITULO DE PÁGINA -->
                <b>{{$componentName}}|{{$pageTitle}}</b>
            </h4>
            <ul class="tabs tab-pills">
                <li>
                    <a href="javascript:void(0)" class="tabmenu bg-dark" data-toggle="modal" data-target="#theModal">Agregar</a>
                </li>
                
            </ul>
        </div>
        <!-- #TODO: BUSCADOR -->
        @include('common.searchbox')
        <div class="widget-content">
            <div class="table-responsive">
                <table class="table table bordered table striped mt-1">
                    <thead class="text-white" style="background:#3BF5C">
                        <tr>
                                <th class="table-th text-white">DESCRIPCIÓN</th>
								<th class="table-th text-white text-center">BARCODE</th>
								<th class="table-th text-white text-center">CATEGORÍA</th>
								<th class="table-th text-white text-center">PRECIO</th>
								<th class="table-th text-white text-center">STOCK</th>
								<th class="table-th text-white text-center">INV.MIN</th>
								<th class="table-th text-white text-center">IMAGEN</th>
								<th class="table-th text-white text-center">ACTIONS</th>
                        </tr>

                    </thead>
                    <tbody>
                        <!-- #TODO:FOREACH QUE RECORRE LA INFORMACION Y LLENA LAS TABLAS -->
                        @foreach($data as $product)
                        <tr>
                                <td><h6 class="text-left">{{$product->name}}</h6></td>
								<td><h6 class="text-center">{{$product->barcode}}</h6></td>
								<td><h6 class="text-center">{{$product->category}}</h6></td>
								<td><h6 class="text-center">{{$product->price}}</h6></td>
								<td>
									<h6 class="text-center {{$product->stock <= $product->alerts ? 'text-danger' : '' }} ">
										{{$product->stock}}
									</h6>
								</td>
								<td><h6 class="text-center">{{$product->alerts}}</h6></td>
                           
                            <td class="text-center">
                                <span><img src="{{ asset('storage/products/' . $product->imagen2 ) }}" alt="imagen de ejemplo" height="70" width="80" class="rounded"></span>
                            </td>
                            <td class="text-center">
                                
                                <a href="javascript:void(0)"wire:click="Edit('{{$product->id}}')" class="btn btn-dark mtmobile" title="Edit"><i class="fas fa-edit"></i></a>
                                <a href="javascript:void(0)"onclick="Confirm('{{$product->id}}')" class="btn btn-dark" title="Delete"><i class="fas fa-trash"></i></a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
              
                {{$data->links()}}
            </div>
        </div>
    </div>
    <!-- #TODO:AGREGAR FORMULARIO -->
  
</div>

@include('livewire.products.form')
</div>
<script>
        document.addEventListener('DOMContentLoaded',function(){
        window.livewire.on('product-added',msg=>{
             $('#theModal').modal('hide');
             noty(msg)
        })
        window.livewire.on('product-updated',msg=>{
             $('#theModal').modal('hide');
             noty(msg)
        })
        window.livewire.on('product-deleted',msg=>{
          
             noty(msg)
        })
        window.livewire.on('modal-hide',msg=>{
             $('#theModal').modal('hide');
          
        })
        window.livewire.on('modal-show',msg=>{
             $('#theModal').modal('show');
            
        })
        // #TODO: eventos vinculados a los errores que podrían darse en el formulario
        window.livewire.on('hidden.bs.modal',msg=>{
             $('.er').modal('display','none');
            
        })
    });
function Confirm(id)
{
    
    swal({
        title:'CONFIRMAR',
        text:'¿CONFIRMAS ELIMINAR EL REGISTRO',
        type:'success',
        showCancelButton:true,
        cancelButtonText:'Cerrar',
        cancelButtonColor:'#fff',
        confirmButtonText:'Aceptar',
        confirmButtonColor:'#3B3F5C'
    }).then(function(result){
        if(result.value){
            window.livewire.emit('deleteRow',id)
            swal.close()
        }
    })
}
</script>